language: java

jdk:
  - openjdk14

sudo: false

export CODECOV_TOKEN="0610a7d4-631d-4d93-bac4-e0752e8805f7"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -nikstar1235@gmail.com
    on_success: never # default: change
    on_failure: always # default: always